VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ErrHandler"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@todo function that will check number of applied names through the files
'@todo function that will check range addresses between consolidated files
'@todo function that will send personalized mail with error information
'@todo error handler that will show custom message on error
