VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Timer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Dim tmpTime As Date

Sub start()
    'initializes tmpTime variable that will store start time
    '@todo decide in what type store time
    
End Sub

Function stopTimer(Optional format As String) As Integer
    'returns difference between time now and tmpTime variable value
    
End Function


